# Basic Settings
edition = "2024"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Auto"

# Import Sorting (Requires Nightly)
imports_granularity = "Crate"
group_imports = "StdExternalCrate"

# Code Readability
wrap_comments = true
format_code_in_doc_comments = true
normalize_comments = true
reorder_impl_items = true

# String & Macro Handling
format_strings = true
format_macro_matchers = true