[package]
name = "ingot-primitives"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
rust_decimal.workspace = true
serde.workspace = true

[dev-dependencies]
anyhow.workspace = true
serde_json.workspace = true

[lints]
workspace = true
